# ============================================================================
# docker-compose.yml - Docker Compose konfigurace
# ============================================================================

version: '3.8'

services:
  fastcentrik-transformer:
    build: .
    container_name: fastcentrik-to-woocommerce
    volumes:
      # Mapování vstupních souborů
      - ./Export_Excel_Lite.xls:/app/Export_Excel_Lite.xls:ro
      # Mapování výstupní složky
      - ./woocommerce_output:/app/woocommerce_output
      # Mapování log souborů
      - ./transformation.log:/app/transformation.log
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    
  # Služba pro jednorázové spuštění transformace
  transform:
    build: .
    container_name: fastcentrik-transform-once
    volumes:
      - ./Export_Excel_Lite.xls:/app/Export_Excel_Lite.xls:ro
      - ./woocommerce_output:/app/woocommerce_output
      - ./transformation.log:/app/transformation.log
    environment:
      - PYTHONUNBUFFERED=1
    command: python run_transformation.py
    profiles:
      - transform